INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);
INSERT INTO users (name, age) VALUES ('Peter', 21);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project1', 'Code', 1, 2, 3);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);